spring:
  datasource:
    url: jdbc:mysql://58.122.188.69:3306/sport
    username: admin
    password: 411311pwy!
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect